

/* Zodiac Sign Function */

CREATE FUNCTION FN_SIGN(@BDATE DATETIME)
RETURNS VARCHAR(20)
AS
BEGIN
	-- USE YEAR 2000 TO MAKE IT EASIER
	SET @BDATE = CAST(DATEPART(m,@bdate) as VARCHAR(10))+ '/' + CAST(DATEPART(d,@bdate) as VARCHAR(10))+ '/2000'
				
	
	DECLARE @SIGN VARCHAR(100)

        SELECT @SIGN =CASE
			 WHEN @BDATE >= '1/1/2000'   AND @BDATE <= '01/20/2000'  THEN  'Capricorn'
			 WHEN @BDATE >= '01/21/2000' AND @BDATE <= '02/19/2000'  THEN  'Aquarius'
			 WHEN @BDATE >= '02/20/2000' AND @BDATE <= '03/20/2000'  THEN  'Pisces'
			 WHEN @BDATE >= '03/21/2000' AND @BDATE <= '04/20/2000'  THEN  'Aries' 
			 WHEN @BDATE >= '04/21/2000' AND @BDATE <= '05/21/2000'  THEN  'Taurus'
			 WHEN @BDATE >= '05/22/2000' AND @BDATE <= '06/21/2000'  THEN  'Gemini'
			 WHEN @BDATE >= '06/22/2000' AND @BDATE <= '07/22/2000'  THEN  'Cancer'
			 WHEN @BDATE >= '07/23/2000' AND @BDATE <= '08/21/2000'  THEN  'Leo'
			 WHEN @BDATE >= '08/22/2000' AND @BDATE <= '09/23/2000'  THEN  'Virgo'
			 WHEN @BDATE >= '09/24/2000' AND @BDATE <= '10/23/2000'  THEN  'Libra'
			 WHEN @BDATE >= '10/24/2000' AND @BDATE <= '11/22/2000'  THEN  'Scorpio'
			 WHEN @BDATE >= '11/23/2000' AND @BDATE <= '12/22/2000'  THEN  'Sagittarius'
			 WHEN @BDATE >= '12/23/2000' AND @BDATE <= '12/31/2000'  THEN  'Capricorn'
			
			
			 ELSE 'HUH'
		      END
	RETURN @SIGN
END
GO

GO
-- RETURNS 2 STRINGS TOGETHER IN ORDER (TO KEEP FROM HAVING "LIBRA & SAGI" AND "SAGI & LIBRA" SHOWING UP DIFFERENTLY
CREATE FUNCTION FN_2SIGNS(@BDATE DATETIME, @BDATEB DATETIME)
RETURNS VARCHAR(40)
AS
BEGIN
	DECLARE @SIGN1 VARCHAR(20)
	DECLARE @SIGN2 VARCHAR(20)
	DECLARE @OUTSIGN VARCHAR(40)
	
	SET @SIGN1 = .DBO.FN_SIGN (@BDATE)
    SET @SIGN2 = .DBO.FN_SIGN (@BDATEB)

	IF (@SIGN1 > @SIGN2)   
	BEGIN 
		SET @OUTSIGN = @SIGN1 + ' ' + @SIGN2
	END
	
	IF (@SIGN2 > @SIGN1)   
	BEGIN
		SET @OUTSIGN = @SIGN2 + ' ' + @SIGN1
	END
	
	IF (@SIGN1 = @SIGN2)   
	BEGIN
		SET @OUTSIGN = @SIGN1 + ' ' + @SIGN2
	END

	RETURN @OUTSIGN
END

GO
-- THE BIG QUERY

-- ORDER BY 
SELECT   MATCH, CNT  FROM (
	-- GROUP BY SUB
	SELECT 	 .DBO.FN_2SIGNS(A,B) MATCH,  COUNT(*) AS CNT
	FROM ( 	-- SUB TO GET THE BIRTHDAYS DISNTICTLY (AVOID DUPES)
		SELECT   DISTINCT H.BIRTHDT A, S.BIRTHDT B
		FROM 	 PPMEMBER H, PPMEMBER S
		WHERE 	 H.RELATIONSHIP = 'H'
		AND	 S.RELATIONSHIP = 'S'
		AND 	 H.TENANTTBLKEY = S.TENANTTBLKEY
		AND	 H.BIRTHDT IS NOT NULL
		AND	 S.BIRTHDT IS NOT NULL 
	) X 
	GROUP BY .DBO.FN_2SIGNS(A,B)
) X
ORDER BY  CNT

GO
DROP FUNCTION  FN_2SIGNS
DROP FUNCTION  FN_SIGN
GO
